"""Add test_logs table

Revision ID: b4d9baa0983a
Revises: 9cf07ff9990c
Create Date: 2025-12-07 08:18:23.016089

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4d9baa0983a"
down_revision: str | Sequence[str] | None = "9cf07ff9990c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_logs",
        sa.Column("test_run_id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("logger", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("exception", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["test_run_id"], ["test_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_test_logs_level"), "test_logs", ["level"], unique=False)
    op.create_index(op.f("ix_test_logs_test_run_id"), "test_logs", ["test_run_id"], unique=False)
    op.create_index(op.f("ix_test_logs_timestamp"), "test_logs", ["timestamp"], unique=False)
    op.drop_index(op.f("idx_failures_test_run_type_name"), table_name="failures")
    op.drop_index(op.f("ix_failures_first_occurrence"), table_name="failures")
    op.drop_index(op.f("ix_failures_name"), table_name="failures")
    op.drop_index(op.f("ix_failures_request_type"), table_name="failures")
    op.drop_index(op.f("ix_failures_test_run_id"), table_name="failures")
    op.create_index("idx_failures_test_run", "failures", ["test_run_id"], unique=False)
    op.alter_column(
        "request_logs",
        "context",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_request_logs_request_type_name"), table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_name"), table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_request_type"), table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_start_time"), table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_test_run_id"), table_name="request_logs")
    op.drop_index(op.f("ix_stats_snapshots_test_run_id"), table_name="stats_snapshots")
    op.drop_index(op.f("ix_stats_snapshots_timestamp"), table_name="stats_snapshots")
    op.alter_column(
        "test_runs",
        "test_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_test_runs_project"), table_name="test_runs")
    op.drop_index(op.f("ix_test_runs_test_name"), table_name="test_runs")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_test_runs_test_name"), "test_runs", ["test_name"], unique=False)
    op.create_index(op.f("ix_test_runs_project"), "test_runs", ["project"], unique=False)
    op.alter_column(
        "test_runs",
        "test_metadata",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.create_index(op.f("ix_stats_snapshots_timestamp"), "stats_snapshots", ["timestamp"], unique=False)
    op.create_index(op.f("ix_stats_snapshots_test_run_id"), "stats_snapshots", ["test_run_id"], unique=False)
    op.create_index(op.f("ix_request_logs_test_run_id"), "request_logs", ["test_run_id"], unique=False)
    op.create_index(op.f("ix_request_logs_start_time"), "request_logs", ["start_time"], unique=False)
    op.create_index(op.f("ix_request_logs_request_type"), "request_logs", ["request_type"], unique=False)
    op.create_index(op.f("ix_request_logs_name"), "request_logs", ["name"], unique=False)
    op.create_index(op.f("idx_request_logs_request_type_name"), "request_logs", ["request_type", "name"], unique=False)
    op.alter_column(
        "request_logs",
        "context",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index("idx_failures_test_run", table_name="failures")
    op.create_index(op.f("ix_failures_test_run_id"), "failures", ["test_run_id"], unique=False)
    op.create_index(op.f("ix_failures_request_type"), "failures", ["request_type"], unique=False)
    op.create_index(op.f("ix_failures_name"), "failures", ["name"], unique=False)
    op.create_index(op.f("ix_failures_first_occurrence"), "failures", ["first_occurrence"], unique=False)
    op.create_index(
        op.f("idx_failures_test_run_type_name"), "failures", ["test_run_id", "request_type", "name"], unique=False
    )
    op.drop_index(op.f("ix_test_logs_timestamp"), table_name="test_logs")
    op.drop_index(op.f("ix_test_logs_test_run_id"), table_name="test_logs")
    op.drop_index(op.f("ix_test_logs_level"), table_name="test_logs")
    op.drop_table("test_logs")
    # ### end Alembic commands ###
